// Raw common-word lists. Anything the wrong length or containing non-letters
// is filtered out at load time in script.js, so approximate lists are fine.

const RAW_WORDS_4 = `
ABLE ACHE ACID ACRE AGED ALSO AMID ARCH AREA ARMY AWAY BABY BACK BAIL BAIT
BAKE BALD BALE BALL BAND BANE BANK BARE BARK BARN BASE BASH BASK BATH BEAD
BEAK BEAM BEAN BEAR BEAT BEEF BEEN BEEP BEER BEET BELL BELT BEND BENT BEST
BIAS BIKE BILE BILL BIND BIRD BITE BLED BLOB BLOG BLOT BLOW BLUE BLUR BOAR
BOAT BODY BOIL BOLD BOLT BOMB BOND BONE BONY BOOK BOOM BOON BOOT BORE BORN
BOSS BOTH BOUT BOWL BOXY BRAG BRAN BRAT BRAY BRED BREW BRIM BROW BUCK BULB
BULK BULL BUMP BUNK BURN BURY BUSH BUSY BUZZ CAGE CAKE CALF CALL CALM CAME
CAMP CANE CAPE CARD CARE CARP CART CASE CASH CAST CAVE CELL CENT CHAP CHAT
CHEF CHEW CHIC CHIN CHIP CHOP CITY CLAD CLAM CLAN CLAP CLAY CLIP CLOG CLOT
CLUB CLUE COAL COAT CODE COIL COIN COLD COLT COMB COME COOK COOL COPE COPY
CORD CORE CORK CORN COST COVE COZY CRAB CRAM CRAY CREW CRIB CROP CROW CUBE
CUFF CULT CURB CURD CURE CURL CURT CUTE DAMP DARE DARK DART DASH DATA DATE
DAWN DAYS DEAD DEAF DEAL DEAN DEAR DEBT DECK DEED DEEM DEEP DEER DENY DESK
DIAL DICE DIET DIME DINE DIRT DISC DISH DOCK DOES DOLL DOME DONE DOOR DOSE
DOTE DOVE DOWN DOZE DRAG DRAW DREW DRIP DROP DRUM DUAL DUCK DUCT DUEL DUKE
DULL DUMB DUNE DUSK DUST DUTY EACH EARN EASE EAST EASY ECHO EDGE EDIT EGGS
ELSE EPIC EVEN EVER EVIL EXIT FACE FACT FADE FAIL FAIR FAKE FALL FAME FARE
FARM FAST FATE FEAR FEAT FEED FEEL FEET FELL FELT FERN FEUD FILE FILL FILM
FIND FINE FIRE FIRM FISH FIST FIVE FLAG FLAT FLAW FLEE FLEW FLEX FLIP FLOW
FLUX FOAM FOLD FOLK FOND FONT FOOD FOOL FOOT FORD FORE FORK FORM FORT FOUL
FOUR FOWL FREE FROG FROM FUEL FULL FUME FUND FUNK FURY FUSE FUSS GAIN GALE
GALL GAME GANG GAPE GASH GASP GATE GAVE GAZE GEAR GENE GIFT GIRL GIVE GLAD
GLOW GLUE GOAL GOAT GOLD GOLF GONE GOOD GORE GRAB GRAD GRAN GRAY GREW GREY
GRID GRIM GRIN GRIP GROW GULF GULP GUSH GUST HAIL HAIR HALE HALF HALL HALT
HAND HANG HARD HARE HARK HARM HARP HATE HAUL HAVE HAWK HAZE HEAD HEAL HEAP
HEAR HEAT HEED HEEL HEIR HELD HELL HELM HELP HERB HERD HERE HERO HIDE HIGH
HILL HINT HIRE HISS HIVE HOLD HOLE HOLY HOME HOMY HONE HOOD HOOF HOOK HOOP
HOOT HOPE HORN HOSE HOST HOUR HUGE HULL HUMP HUNG HUNT HURL HURT HUSH HYMN
ICON IDEA IDLE INCH IRON ITEM JADE JAIL JAZZ JOIN JOKE JOLT JUMP JUNE JUNK
JURY JUST KEEN KEEP KELP KEPT KICK KILL KIND KING KISS KITE KNEE KNEW KNIT
KNOB KNOT KNOW LACE LACK LADY LAID LAKE LAMB LAME LAMP LAND LANE LARK LASH
LAST LATE LAVA LAWN LAZY LEAD LEAF LEAK LEAN LEAP LEFT LEND LENS LESS LEST
LICK LIED LIFE LIFT LIKE LILY LIMB LIME LIMP LINE LINK LION LISP LIST LIVE
LOAD LOAF LOAN LOBE LOCK LOFT LOGO LONE LONG LOOK LOOM LOOP LOOT LORD LOSE
LOSS LOST LOUD LOVE LUCK LULL LUMP LUNG LURE LURK LUSH LUST MACE MADE MAID
MAIL MAIN MAKE MALE MALL MANE MANY MAPS MARE MARK MASH MASK MASS MAST MATE
MATH MAZE MEAL MEAN MEAT MEET MELT MEMO MENU MERE MESH MESS MICE MILD MILE
MILK MILL MIME MIND MINE MINT MISS MIST MOAN MOAT MOCK MODE MOLD MOLE MONK
MOOD MOON MOOR MOOT MORE MOSS MOST MOTH MOVE MUCH MUCK MUFF MULE MUSE MUSH
MUST MUTE NAIL NAME NAVY NEAR NEAT NECK NEED NERD NEST NEWS NEXT NICE NICK
NINE NODE NONE NOON NORM NOSE NOTE NOUN NUDE NULL NUMB NUTS OATH OBEY ODOR
OKAY OMEN ONCE ONLY ONTO OPEN ORAL OVAL OVEN OVER PACE PACK PACT PAGE PAID
PAIL PAIN PAIR PALE PALM PANE PANG PANT PARK PART PASS PAST PATH PAVE PAWN
PEAK PEAR PEAT PEEK PEEL PEEP PEER PERK PEST PICK PIER PILE PILL PINE PINK
PINT PIPE PITY PLAN PLAY PLEA PLOT PLOW PLOY PLUG PLUM PLUS POEM POET POKE
POLE POLL POND PONY POOL POOR PORE PORK PORT POSE POST POUR PRAY PREY PRIM
PROD PROM PROP PROS PUFF PUMP PUNK PUNY PURE PUSH QUIT QUIZ RACE RACK RAFT
RAGE RAID RAIL RAIN RAKE RAMP RANK RARE RASH RATE RAVE READ REAL REAP REAR
REED REEF REEL RELY REND RENT REST RICE RICH RIDE RIFT RIME RING RINK RIOT
RIPE RISE RISK RITE ROAD ROAM ROAR ROBE ROCK RODE ROLE ROLL ROOF ROOM ROOT
ROPE ROSE ROSY ROTE ROUT ROVE RUDE RUIN RULE RUNG RUNT RUSH RUST SACK SAFE
SAGE SAID SAIL SAKE SALE SALT SAME SAND SANE SASH SAVE SCAN SCAR SEAL SEAM
SEAR SEAT SEED SEEK SEEM SEEN SEER SELF SELL SEND SENT SHED SHIP SHOE SHOP
SHOT SHOW SHUT SICK SIDE SIFT SIGH SIGN SILK SILL SILT SING SINK SIRE SITE
SIZE SKID SKIM SKIN SKIP SKIT SLAB SLAM SLAP SLAY SLED SLEW SLID SLIM SLIP
SLIT SLOB SLOG SLOP SLOT SLOW SLUG SLUM SLUR SMOG SNAG SNAP SNIP SNOB SNOW
SOAK SOAP SOAR SOCK SODA SOFA SOFT SOIL SOLD SOLE SOME SONG SOON SOOT SORE
SORT SOUL SOUP SOUR SOWN SPAN SPAR SPAT SPIN SPIT SPOT SPRY SPUN SPUR STAB
STAG STAR STAY STEM STEP STEW STIR STOP STOW STUB STUD STUN SUCH SUED SUIT
SULK SUNG SUNK SURE SURF SWAM SWAN SWAP SWAY SWIM SWUM TACK TAIL TAKE TALE
TALK TALL TAME TANK TAPE TASK TAXI TEAM TEAR TECH TEEM TEEN TELL TEND TENT
TERM TEST TEXT THAN THAT THAW THEM THEN THEY THIN THIS THUD THUG TICK TIDE
TIDY TIED TIER TILE TILL TILT TIME TINT TINY TIRE TOAD TOIL TOLD TOLL TOMB
TONE TOOK TOOL TOOT TORE TORN TOSS TOUR TOWN TRAM TRAP TRAY TREE TREK TRIM
TRIO TRIP TROT TRUE TUBE TUCK TUFT TUNA TUNE TURF TURN TUSK TWIN TWIT TYPE
UGLY UNIT UPON URGE USED USER VAIN VALE VARY VASE VAST VEAL VEER VEIL VEIN
VENT VERB VERY VEST VETO VICE VIEW VILE VINE VISA VOID VOTE WADE WAGE WAIL
WAIT WAKE WALK WALL WAND WANE WANT WARD WARE WARM WARN WARP WARY WASH WASP
WAVE WAVY WEAK WEAR WEED WEEK WEEP WELD WELL WENT WEPT WERE WEST WHAT WHEN
WHIM WHIP WHIT WHIZ WHOA WHOM WIDE WIFE WILD WILL WILT WIND WINE WING WINK
WIPE WIRE WISE WISH WITH WOKE WOLF WOMB WOOD WOOL WORD WORE WORK WORM WORN
WRAP WREN YARD YARN YAWN YEAR YELL YOGA YOKE YOLK YOUR ZERO ZEST ZONE ZOOM
`;

const RAW_WORDS_5 = `
ABIDE ABOUT ABOVE ADAPT ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD
ALARM ALBUM ALERT ALIKE ALIVE ALLOW ALONE ALONG ALOUD ALTER AMONG AMPLE
ANGEL ANGER ANGLE ANGRY ANKLE APART APPLE APPLY ARENA ARGUE ARISE ARMOR
AROMA ARRAY ARROW ASIDE ASSET AUDIO AUDIT AVOID AWAIT AWAKE AWARD AWARE
BADGE BADLY BAKER BASIC BASIN BASIS BATCH BATHE BEACH BEARD BEAST BEGAN
BEGIN BEGUN BEING BELOW BENCH BERRY BIGHT BIRTH BLACK BLADE BLAME BLANK
BLAST BLAZE BLEED BLEND BLESS BLIND BLINK BLISS BLOCK BLOND BLOOD BLOOM
BLOWN BLUFF BLUNT BLUSH BOARD BOAST BONUS BOOST BOOTH BORNE BOUND BRACE
BRAIN BRAKE BRAND BRASS BRAVE BREAD BREAK BREED BRICK BRIDE BRIEF BRING
BRISK BROAD BROIL BROKE BROOK BROOM BROTH BROWN BRUSH BUILD BUILT BUNCH
BURST CABIN CABLE CACHE CANDY CANOE CARGO CARRY CARVE CATCH CAUSE CEASE
CHAIN CHAIR CHALK CHAMP CHAOS CHARM CHART CHASE CHEAP CHEAT CHECK CHEEK
CHEER CHESS CHEST CHIEF CHILD CHILL CHIME CHOIR CHOKE CHORD CHOSE CHUNK
CIVIC CIVIL CLAIM CLAMP CLASH CLASP CLASS CLEAN CLEAR CLERK CLICK CLIFF
CLIMB CLING CLOCK CLONE CLOSE CLOTH CLOUD CLOWN CLUCK COACH COAST COVER
COYLY CRACK CRAFT CRANE CRASH CRAWL CRAZY CREAM CREEK CREEP CREST CRIME
CRISP CROOK CROSS CROWD CROWN CRUDE CRUEL CRUMB CRUSH CRUST CURVE CYCLE
DADDY DAILY DAIRY DANCE DATED DEATH DEBUT DECAY DECOR DELAY DELTA DENSE
DEPTH DERBY DIARY DIGIT DIRTY DITCH DIVER DODGE DOING DONOR DONUT DOUBT
DOUGH DOZEN DRAFT DRAIN DRAKE DRAMA DRANK DRAWN DREAD DREAM DRESS DRIED
DRIFT DRILL DRINK DRIVE DROVE DROWN DRUNK DRYER DUCHY DULLY DUSTY DUTCH
DWELL EAGER EAGLE EARLY EARTH EASEL EIGHT ELBOW ELDER ELECT ELITE EMBER
EMPTY ENJOY ENTER ENTRY EQUAL ERASE ERROR ESSAY EVENT EVERY EXACT EXIST
EXTRA FABLE FAINT FAIRY FAITH FALSE FANCY FATAL FAULT FAVOR FEAST FENCE
FERRY FETCH FEVER FIBER FIELD FIERY FIFTH FIFTY FIGHT FILTH FINAL FINCH
FIRST FISHY FIXED FJORD FLAIR FLAKE FLAME FLASH FLEET FLESH FLICK FLING
FLINT FLIRT FLOAT FLOCK FLOOD FLOOR FLORA FLOUR FLOWN FLUFF FLUID FLUSH
FOCAL FOCUS FORCE FORGE FORGO FORTH FORTY FORUM FOUND FRAME FRANK FRAUD
FRESH FRIED FROND FRONT FROST FROWN FROZE FRUIT FUDGE FUNNY FUSSY GAUGE
GHOST GIANT GIVEN GLADE GLARE GLASS GLAZE GLEAM GLIDE GLINT GLOBE GLOOM
GLORY GLOVE GOING GOOSE GRACE GRADE GRAIN GRAND GRANT GRAPE GRAPH GRASP
GRASS GRAVE GRAVY GRAZE GREAT GREED GREEK GREEN GREET GRIEF GRILL GRIME
GRIND GROIN GROOM GROSS GROUP GROVE GROWL GROWN GUARD GUESS GUEST GUIDE
GUILD GUILT HABIT HAPPY HARSH HASTE HATCH HAVEN HEARD HEART HEAVY HEDGE
HELLO HENCE HINGE HOBBY HONEY HONOR HORSE HOTEL HOUND HOUSE HOVER HUMAN
HUMID HUMOR HUNCH HURRY HUSKY HYPER ICING IDEAL IDIOM IGLOO IMAGE IMPLY
INBOX INDEX INNER INPUT ISSUE IVORY JELLY JOINT JOKER JOLLY JUDGE JUICE
JUMBO JUMPY JUROR KNEEL KNIFE KNOCK KNOWN LABEL LABOR LARGE LASER LATCH
LATER LAUGH LAYER LEAFY LEARN LEASE LEAST LEAVE LEDGE LEMON LEVEL LEVER
LIGHT LIMIT LINEN LIVER LOCAL LODGE LOGIC LOOSE LOWER LOYAL LUCKY LUNAR
LUNCH LUNGE LYRIC MACRO MAGIC MAJOR MAKER MANGO MAPLE MARCH MARSH MATCH
MAYOR MEDAL MEDIA MELON MERCY MERGE MERIT METAL MICRO MIDST MIGHT MINOR
MINUS MIRTH MODAL MODEL MOIST MOLAR MONEY MONTH MOTOR MOUND MOUNT MOUSE
MOUTH MOVED MOVIE MUSIC NAIVE NASTY NEEDY NERVE NEVER NEWLY NIGHT NOBLE
NOISE NORTH NOVEL NURSE OCEAN OFFER OLIVE ONION OPERA ORBIT ORDER ORGAN
OTHER OUGHT OUTER OWNER OZONE PANEL PANIC PAPER PARTY PASTA PASTE PATCH
PAUSE PEACE PEACH PEARL PEDAL PENNY PHASE PHONE PHOTO PIANO PIECE PILOT
PITCH PIVOT PIZZA PLACE PLAID PLAIN PLANE PLANT PLATE PLAZA PLUMB POINT
POKER POLAR POUND POWER PRESS PRICE PRIDE PRIME PRINT PRIOR PRIZE PROOF
PROUD PROVE PUPIL PUPPY QUEEN QUERY QUEST QUICK QUIET QUILT QUIRK QUOTE
RADAR RADIO RAISE RALLY RANCH RANGE RAPID RATIO REACH REACT READY REALM
REBEL REFER RELAX REPLY RESET RIDGE RIFLE RIGHT RIVAL RIVER ROAST ROBIN
ROBOT ROCKY ROMAN ROUGH ROUND ROUTE ROYAL RUGBY RUMOR RURAL SADLY SAINT
SALAD SALON SANDY SAUCE SAVOR SCALE SCARE SCARF SCENE SCENT SCOLD SCOOP
SCOPE SCORE SCOUT SCRAP SCREW SCRUB SENSE SERVE SEVEN SHADE SHADY SHAKE
SHALL SHAME SHAPE SHARE SHARK SHARP SHAVE SHEEP SHEET SHELF SHELL SHIFT
SHINE SHINY SHIRT SHOCK SHONE SHOOT SHORE SHORT SHOUT SHOVE SHOWN SHREW
SHRUB SHUNT SIGHT SILLY SINCE SIXTY SKILL SKIRT SKULL SLANG SLEEP SLICE
SLICK SLIDE SLING SLOPE SLOTH SMALL SMART SMASH SMELL SMILE SMOKE SNACK
SNAIL SNAKE SOLAR SOLID SOLVE SORRY SOUND SOUTH SPACE SPARE SPARK SPEAK
SPEED SPELL SPEND SPENT SPICE SPIKE SPILL SPINE SPIRE SPLIT SPOIL SPOKE
SPOON SPORT SPRAY STACK STAFF STAGE STAIN STAIR STAKE STALE STALK STALL
STAMP STAND STARE START STASH STATE STEAK STEAL STEAM STEEL STEEP STEER
STICK STIFF STILL STING STOCK STOMP STONE STOOD STOOL STORE STORK STORM
STORY STOUT STOVE STRAY STRIP STUCK STUDY STUFF STUMP STYLE SUGAR SUITE
SUNNY SUPER SURGE SWAMP SWARM SWEAR SWEAT SWEEP SWEET SWELL SWIFT SWING
SWIRL SWORD SWORE SWORN TABLE TAINT TALON TASTE TEACH TEETH TEMPO TENSE
TENTH THANK THEFT THEIR THEME THERE THESE THICK THIEF THING THINK THIRD
THORN THOSE THREE THREW THROB THROW THUMB THUMP TIGER TIGHT TILDE TIMID
TITLE TOAST TODAY TOKEN TONIC TOOTH TOPIC TORCH TOTAL TOUCH TOUGH TOWEL
TOWER TOXIC TRACE TRACK TRADE TRAIL TRAIN TRAIT TRAMP TRASH TREAD TREAT
TREND TRIAL TRIBE TRICK TRIED TRIPE TROOP TRUCE TRUCK TRULY TRUNK TRUST
TRUTH TUNIC TWICE TWINE TWIRL TWIST TYPED ULTRA UNCLE UNDER UNIFY UNION
UNITE UNTIL UPPER UPSET URBAN USAGE USUAL VAGUE VALID VALOR VALUE VAPOR
VAULT VENOM VENUE VERSE VIDEO VIGIL VIRUS VISIT VISOR VITAL VIVID VOCAL
VODKA VOICE VOTER WAGON WAIST WAIVE WATCH WATER WAVED WEARY WEAVE WEDGE
WEIGH WEIRD WELSH WHALE WHEAT WHEEL WHERE WHICH WHILE WHINE WHISK WHITE
WHOLE WHOSE WIDEN WIDOW WIDTH WIELD WOMAN WOMEN WOODY WORLD WORRY WORSE
WORST WORTH WOULD WOUND WOVEN WRATH WRECK WRIST WRITE WRONG YACHT YEAST
YIELD YOUNG YOUTH ZEBRA
`;
